package com.example.myapplication2.constants

object BaseVariables {
    val LANGUAGES = listOf(
        "Arabic",
        "Belarusian",
        "Czech",
        "Welsh",
        "German",
        "Greek",
        "English",
        "French",
        "Croatian",
        "Hungarian",
        "Icelandic",
        "Italian",
        "Japanese",
        "Georgian",
        "Korean",
        "Macedonian",
        "Malay",
        "Polish",
        "Dutch",
        "Norwegian",
        "Portuguese",
        "Russian",
        "Slovakian",
        "Slovenian",
        "Spanish",
        "Swedish",
        "Turkish",
        "Ukrainian",
        "Chinese",
    )

    val LANGUAGES_SHORT = listOf(
        "ar",
        "be",
        "cs",
        "cy",
        "de",
        "el",
        "en",
        "fr",
        "hr",
        "hu",
        "is",
        "it",
        "ja",
        "ka",
        "ko",
        "mk",
        "ms",
        "nl",
        "no",
        "pl",
        "pt",
        "ru",
        "sk",
        "sl",
        "es",
        "sv",
        "tr",
        "uk",
        "zh",
    )

    val LANGUAGES_BCP47 = mapOf(
        "ar" to "ar-SA",
        "be" to "be-BY",
        "cs" to "cs-CZ",
        "cy" to "cy-GB",
        "de" to "de-DE",
        "el" to "el-GR",
        "en" to "en-US",
        "fr" to "fr-FR",
        "hr" to "hr-HR",
        "hu" to "hu-HU",
        "is" to "is-IS",
        "it" to "it-IT",
        "ja" to "ja-JP",
        "ka" to "ka-GE",
        "ko" to "ko-KR",
        "mk" to "mk-MK",
        "ms" to "ms-MY",
        "nl" to "nl-NL",
        "no" to "no-NO",
        "pl" to "pl-PL",
        "pt" to "pt-PT",
        "ru" to "ru-RU",
        "sk" to "sk-SK",
        "sl" to "sl-SI",
        "es" to "es-ES",
        "sv" to "sv-SE",
        "tr" to "tr-TR",
        "uk" to "uk-UA",
        "zh" to "zh-CN"
    )
}
