package com.example.myapplication2.constants

object BaseVariables {
    val LANGUAGES = listOf(
        "Arabic",
        "Belarusian",
        "Czech",
        "Welsh",
        "German",
        "Greek",
        "English",
        "French",
        "Croatian",
        "Hungarian",
        "Icelandic",
        "Italian",
        "Japanese",
        "Georgian",
        "Korean",
        "Macedonian",
        "Malay",
        "Polish",
        "Dutch",
        "Norwegian",
        "Portuguese",
        "Russian",
        "Slovakian",
        "Slovenian",
        "Spanish",
        "Swedish",
        "Turkish",
        "Ukrainian",
        "Chinese",
    )

    val LANGUAGES_SHORT = listOf(
        "ar",
        "be",
        "cs",
        "cy",
        "de",
        "el",
        "en",
        "fr",
        "hr",
        "hu",
        "is",
        "it",
        "ja",
        "ka",
        "ko",
        "mk",
        "ms",
        "nl",
        "no",
        "pl",
        "pt",
        "ru",
        "sk",
        "sl",
        "es",
        "sv",
        "tr",
        "uk",
        "zh",
    )
}
